# Project language
language: php

# Versions of PHP you want your project run with.
php:
  - '7.0'

# Allows use container-based infrastructure
sudo: false

# Start mysql service
services:
  - mysql
  - elasticsearch

#ElasticSearch takes few seconds to start, to make sure it is available when the build script runs add a small delay to your build script
before_script:
  - sleep 10
 
 # Cache composer packages so "composer install" is faster
 # attention provoque erreur : Could not parse .travis.yml 
#cache:
#  directories:
#- $HOME/.composer/cache/files
  
# Define an environment variable
env:
- SYMFONY_VERSION="4.0.*" DB=mysql

# Update composer
before_install:
  - mysql -e 'CREATE DATABASE IF NOT EXISTS test;'
#  - sudo mysql -e "use mysql; update user set authentication_string=PASSWORD('trigano07') where User='root'; update user set plugin='mysql_native_password';FLUSH PRIVILEGES;"
#  - sudo mysql_upgrade -u root -ptrigano07
#  - sudo mysql_upgrade -u root --force
#  - sudo service mysql restart
  - sudo mysql -u root --default-character-set=utf8 test < tests/trigano_finance_com.sql

# Install composer dependencies,
# Create database, schema and fixtures
install:
  - composer install
  - ./vendor/bin/simple-phpunit install
  - cp .env.travis .env
#  - php bin/console doctrine:database:create --env=test
#  - php bin/console doctrine:schema:create --env=test
#  - php bin/console doctrine:fixtures:load -n --env=test
  
# Run script
script:
  - ./vendor/bin/simple-phpunit
  
# After a build, send email notification with the build results
notifications:
 email: amorel@trigano.fr
 on_success: never
 on_failure: always
 
 
