# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: fr
    app_locales: [fr, en] # rajouté aurore
    exercice: 2019 #init exercice, puis exercice passé dans twig.yaml
    sonata.media.provider.image.class: 		App\Application\Sonata\MediaBundle\Provider\MyImageProvider
    sonata.media.provider.file.class: 		App\Application\Sonata\MediaBundle\Provider\MyFileProvider
    sonata.media.thumbnail.format: 		 	App\Application\Sonata\MediaBundle\Thumbnail\MyFormatThumbnail

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
        public: false       # Allows optimizing the container by removing unused services; this also means
                            # fetching services directly from the container via $container->get() won't work.
                            # The best practice is to be explicit about your dependencies anyway.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/*'
        exclude: '../src/{Entity,Migrations,Tests,Application,Kernel.php}'

    # controllers are imported separately to make sure services can be injected
    # as action arguments even if you don't extend any base controller class
    App\Controller\:
        resource: '../src/Controller'
        tags: ['controller.service_arguments']

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones

    
    admin.document:
        class: App\Admin\DocumentAdmin
        arguments: [~, App\Entity\Document, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Document, group: Documents,  icon: <i class="fa fa-file"></i>, keep_open: true }
        public: true
    admin.page:
        class: App\Admin\PageAdmin
        arguments: [~, App\Entity\Page, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Page, group: Page, on_top: true, icon: <i class="fa fa-file-text"></i> }
        public: true
    admin.categorie:
        class: App\Admin\CategorieAdmin
        arguments: [~, App\Entity\Categorie, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Categorie, group: Menu, on_top: true , icon: <i class="fa fa-sitemap"></i> }
        public: true
    admin.offre_emploi:
        class: App\Admin\OffreEmploiAdmin
        arguments: [~, App\Entity\OffreEmploi, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Offres Emploi, group: Offres Emploi, on_top: true, icon: <i class="fa fa-briefcase"></i> }
        public: true 
    admin.documentfile:
        class: App\Admin\DocumentFileAdmin
        arguments: [~, App\Entity\DocumentFile, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Document File, show_in_dashboard: false }
        public: true
    admin.document_type:
        class: App\Admin\DocumentTypeAdmin
        arguments: [~, App\Entity\DocumentType, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Document Type, group: Paramètres, icon: <i class="fa fa-cog"></i> }
        public: true 
    import.csvtoarray: # pour command.php
        class: App\Services\ConvertCsvToArray
        public: true
    app.menu_listener: # pour sous menu dans BO
        class: App\EventListener\MenuBuilderListener
        tags:
            - { name: kernel.event_listener, event: sonata.admin.event.configure.menu.sidebar, method: addMenuItems }
    sonata.block.service.agenda:
        class: App\Application\Sonata\BlockBundle\Block\AgendaBlockService
        arguments: 
            - "sonata.block.service.agenda"
            - "@templating"
            - "@doctrine.orm.entity_manager"
        tags:
            - { name: sonata.block }